### ISSUE TITLE
NSSortDescriptor hint was helpful, but need a little more dure to case sensitivity.

### ISSUE THREAD

**Issue by dfenjves** [learn-co-curriculum/iOShopping-Cart#8]
Had to use caseInsensitiveCompare, but hadn't had experience with it up until now. Either change names of food, or add a hint to use selector...

**Comment by markedwardmurray** [comment]
lowercased all strings in the spec file so the `@selector(caseInsensitiveCompare:)` option on `NSSortDescriptor` is not needed to solve

https://github.com/learn-co-curriculum/iOShopping-Cart/commit/3a1481c8877707477ebd456d6ee87bccd0b6edfa
